LLVM_VERSION="8.0.1"
OSX_DEPLOYMENT_TARGET="10.12"
BUILD_DIR=`pwd`

echo "Setting up build dir.."
pwd
ls
mkdir tarball

# download LLVM source code
wget https://github.com/llvm/llvm-project/releases/download/llvmorg-$LLVM_VERSION/llvm-$LLVM_VERSION.src.tar.xz
tar xf llvm-$LLVM_VERSION.src.tar.xz
mv llvm-$LLVM_VERSION.src/* llvm
ls
cd llvm
ls
# make build dir and run cmake
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET=$OSX_DEPLOYMENT_TARGET -DCMAKE_INSTALL_PREFIX=$BUILD_DIR/tarball/llvm -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_BUILD_TOOLS=OFF -DLLVM_INCLUDE_TOOLS=OFF -DLLVM_BUILD_EXAMPLES=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_BUILD_TESTS=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_DOCS=OFF -DLLVM_BUILD_UTILS=OFF -DLLVM_INCLUDE_UTILS=OFF -DLLVM_INCLUDE_GO_TESTS=OFF -DLLVM_BUILD_BENCHMARKS=OFF -DLLVM_INCLUDE_BENCHMARKS=OFF -DLLVM_ENABLE_LIBPFM=OFF -DLLVM_ENABLE_ZLIB=OFF -DLLVM_ENABLE_DIA_SDK=OFF -DLLVM_BUILD_INSTRUMENTED_COVERAGE=OFF -DLLVM_ENABLE_BINDINGS=OFF -DLLVM_ENABLE_RTTI=ON -DLLVM_ENABLE_TERMINFO=OFF -LLVM_ENABLE_LIBXML2=OFF -DLLVM_ENABLE_WARNINGS=OFF -DLLVM_POLLY_BUILD=OFF -DLLVM_POLLY_LINK_INTO_TOOLS=OFF ..
ls
cd ..
pwd
echo "Setup complete."
touch SETUP_COMPLETE
